appRecipe/urls.py
from django.conf.urls import patterns, url, include
from recipe import settings

from appRecipe import views

urlpatterns = patterns('',
  url(r'^$', views.home, name='home'),
  # ex: /recipes/
  url(r'^recipes/$', views.recipeIndex, name='recipeIndex'),
  url(r'^recipes/sortby/(?P<sortby>.*)$', views.recipeIndex, name='recipeIndexSorted'),
  # ex: /recipes/3/
  url(r'^recipes/(?P<recipe_id>\d+)/$', views.recipeDetail, name='recipeDetail'),
  # ex: /recipes/3/ingredients
  url(r'^recipes/(?P<recipe_id>\d+)/bottom/(?P<bottom>[^/]+)$', views.recipeDetail, name='recipeDetailBottom'),
  url(r'^recipes/(?P<recipe_id>\d+)/bottom/(?P<bottom>[^/]+)/sortby/(?P<sortby>[^/]+)$', views.recipeDetail, name='recipeDetailBottomSortBy'),
  url(r'^recipes/(?P<recipe_id>\d+)/reviews/add$', views.addReview, name='addReview'),
  url(r'^recipes/(?P<recipe_id>\d+)/favorite/$', views.addToFavorites, name='addToFavorites'),
  url(r'^recipes/(?P<recipe_id>\d+)/unfavorite/$', views.removeFromFavorites, name='removeFromFavorites'),
  url(r'^recipes/(?P<recipe_id>\d+)/pdf/$', views.download_pdf, name='downloadRecipePDF'),
  url(r'^recipes/add/$', views.addRecipe, name='addRecipe'),
  url(r'^recipes/(?P<recipeID>\d+)/edit/$', views.editRecipe, name='editRecipe'),

  url(r'^chefs/$', views.chefIndex, name='chefIndex'),
  url(r'^chefs/sortby/(?P<sortby>.*)$', views.chefIndex, name='chefIndexSorted'),
  url(r'^chefs/(?P<chef_id>\d+)/$', views.chefDetail, name='chefDetail'),
  url(r'^chefs/(?P<chef_id>\d+)/show/(?P<showrecipes>.*)$', views.chefDetail, name='chefDetailShowRecipes'),
  url(r'^chefs/add/$', views.addChef, name='addChef'),
#  url(r'^chefs/edit/$', views.editChef, name='editChef'), 
  url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'recipe/login.html'}),
  url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/'}),

  url(r'^search/', include('haystack.urls')),


  url(r'^test/$', views.test),
  url(r'^staticfiles/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
)

'''url(r'^getPic/(?P<pic_name>(\d|\D)+)/$', views.getPic, name='getPic'),'''

recipe/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'recipe.views.home', name='home'),
    # url(r'^recipe/', include('recipe.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    
    url(r'', include('appRecipe.urls')),
)

appRecipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

from smartfile import BasicClient

from appRecipe import util

# Create your models here.
class Chef(User):
  #Relations
  favoriteRecipes = models.ManyToManyField('Recipe',related_name='chefsWithFavorite', through='Chef_favoriteRecipes')

class Chef_favoriteRecipes(models.Model):
  #Relations
  chef = models.ForeignKey(Chef)
  recipe = models.ForeignKey('Recipe')

class Ingredient(models.Model):
  name = models.CharField(max_length = 200)

class UnitOfMeasure(models.Model):
  name = models.CharField(max_length=50) # Make these singular and use Django's pluralizations?

class RecipeIngredient(models.Model):
  amount = models.FloatField()
  #Relations
  unit = models.ForeignKey(UnitOfMeasure)
  ingredient = models.ForeignKey(Ingredient)
  recipe = models.ForeignKey('Recipe')
  
class Recipe(models.Model):
  name = models.CharField(max_length=200)
  prepTime = models.IntegerField(blank=True,null=True)
  cookTime = models.IntegerField(blank=True,null=True)
  chefComment = models.CharField(max_length=500)
  dateCreated = models.DateTimeField(auto_now_add=True)
  averageRating = models.IntegerField(default=0)
  #Relations
  mainPicture = models.ForeignKey('RecipePicture',blank=True,null=True, related_name = 'mainPictureForRecipe')
  chef = models.ForeignKey(Chef)
  previousVersion = models.ForeignKey('self',blank=True,null=True)
  ingredients = models.ManyToManyField(Ingredient, through=RecipeIngredient)

  def totalTime(self):
    return self.prepTime+self.cookTime

  def totalTimeString(self):
    return util.timeString(self.totalTime())

  def prepTimeString(self):
    return util.timeString(self.prepTime)

  def cookTimeString(self):
    return util.timeString(self.cookTime)

  def review(self, chef, comment, rating):
    self.review_set.create(chef=chef,comment=comment,rating=rating)
    self.averageRating = int(self.review_set.all().aggregate(Avg('rating'))['rating__avg']+.5)
    self.save()
  
class Instruction(models.Model):
  text = models.CharField(max_length=500)
  #Relations
  recipe = models.ForeignKey(Recipe)

class Picture(models.Model):
  path = models.CharField(max_length=500)
  smallpath = models.CharField(max_length=500)

  def setSmallPath(self, fileName, pictureFolder):
    api = BasicClient('VATx6OASrU4KYLaWshrxIvyyYUIl8x','xkpKJ3Wti1cXilKJYnMSqaOLvmNnwe')
    #creating link to picture
    response = api.post('/link',path=pictureFolder+fileName,read=True)
    self.smallpath = response['href']+fileName
    self.save()

  def setPath(self, fileName, pictureFolder):
    api = BasicClient('VATx6OASrU4KYLaWshrxIvyyYUIl8x','xkpKJ3Wti1cXilKJYnMSqaOLvmNnwe')
    #creating link to picture
    response = api.post('/link',path=pictureFolder+fileName,read=True)
    self.path = response['href']+fileName
    self.save()

class RecipePicture(Picture):
  #Relations
  recipe = models.ForeignKey(Recipe)
  
class ChefPicture(Picture):
  #Relations
  chef = models.OneToOneField(Chef)
  
class Review(models.Model):
  comment = models.CharField(max_length=500)
  rating = models.IntegerField()
  dateCreated = models.DateTimeField(auto_now=True)
  #Relations
  chef = models.ForeignKey(Chef)
  recipe = models.ForeignKey(Recipe)

appRecipe/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class AddChef(UserCreationForm):
	first_name = forms.CharField(required=True)
	last_name = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	chef_picture = forms.ImageField(required=False)


class AddRecipe(forms.Form):
	recipe_Name = forms.CharField()
	prep_Time = forms.IntegerField()
	cook_Time = forms.IntegerField()
	comments = forms.CharField(widget=forms.Textarea)
	picture = forms.ImageField(required=False)
	instructions = forms.CharField(widget=forms.Textarea)
	inst = forms.IntegerField(widget=forms.HiddenInput())
	ings = forms.IntegerField(widget=forms.HiddenInput())
	pics = forms.IntegerField(widget=forms.HiddenInput(), required=False)

	def __init__(self, *args, **kwargs):
		extra_fields = kwargs.pop('extra',0)
		extra_ings = max(kwargs.pop('ings',0),1)
		extra_pics = kwargs.pop('pics',0)

		super(AddRecipe, self).__init__(*args, **kwargs)
		self.instrs = []
		self.fields['inst'].initial = extra_fields
		self.fields['ings'].initial = extra_ings
		self.fields['pics'].initial = extra_pics

		for i in range(int(extra_fields)):
			self.fields['extra_fields_{index}'.format(index=i)] = forms.CharField(required=False, widget=forms.Textarea)

		for i in range(int(extra_ings)):
			self.fields['extra_ings_{index}'.format(index=i)] = forms.CharField(required=False)

		for i in range(int(extra_pics)):
			self.fields['id_picture_{index}'.format(index=i)] = forms.ImageField(required=False)


#class Login(forms.Form):
#	username = forms.CharField()
#	password = forms.CharField(widget=forms.PasswordInput)

appRecipe/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import Context, loader
from django.shortcuts import render, get_object_or_404 #, get_list_or_404
from appRecipe.models import Recipe, Chef, ChefPicture, RecipePicture, Ingredient, UnitOfMeasure, RecipeIngredient, Chef_favoriteRecipes
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from appRecipe import forms

from smartfile import BasicClient

from threading import Thread

import Image
import os
import sys
#import zlib

def home(request):
  recipeOfTheDay = Recipe.objects.get(id=4)
  featuredRecipe1 = Recipe.objects.get(id=1)
  featuredRecipe2 = Recipe.objects.get(id=2)
  featuredRecipe3 = Recipe.objects.get(id=3)
  context = { 'recipeOfTheDay' : recipeOfTheDay, 
              'featuredRecipe1' : featuredRecipe1,
              'featuredRecipe2' : featuredRecipe2,
              'featuredRecipe3' : featuredRecipe3,}
  return render(request, 'recipe/home.html', context)

def recipeIndex(request, sortby = 'HighestRated'):
  if sortby == 'Newest':
    recipe_list = Recipe.objects.all().order_by('id').reverse()
  elif sortby == 'AtoZ':
    recipe_list = Recipe.objects.all().order_by('name')
  else:
    recipe_list = Recipe.objects.all().order_by('averageRating').reverse()
    sortby = 'HighestRated'

  recipesPerPage = 10

  ret = getItemListAndPageList(recipe_list, recipesPerPage, request)
  recipes = ret[0]
  pages = ret[1]

  context = { 'recipe_list': recipes,
              'pages':pages,
              'sortby':sortby,}
  return render(request, 'recipe/recipeIndex.html',context)

def getItemListAndPageList(ls, perPage, request):
  paginator = Paginator(ls, perPage)

  page = request.GET.get('page')
  try:
    sublist = paginator.page(page)
    page = int(page)
  except PageNotAnInteger:
    # if page is not an integer, deliver first page.
    sublist = paginator.page(1)
    page = 1
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    sublist = paginator.page(paginator.num_pages)
    page = paginator.num_pages

  pages = None
  
  if (paginator.num_pages > 1):
    startPage = max(1,page-2)
    finishPage = min(startPage+4,paginator.num_pages)
    startPage = max(1, finishPage - 4)
    pages = range(startPage,finishPage + 1)

  return (sublist, pages)
  
def recipeDetail(request, recipe_id,bottom="ReciCopies",sortby="HighestRated"):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  review = None

  if bottom=="Reviews":
    if request.user.is_authenticated():
      revList = recipe.review_set.filter(chef_id=request.user.id)
      if revList.count() > 0:
        review = revList[0]

    bottom_list = recipe.review_set.order_by('dateCreated').reverse()[:5]

  else: #if bottom=="ReciCopies":
    if sortby == 'Newest':
      bottom_list = recipe.recipe_set.all().order_by('id').reverse()
    elif sortby == 'AtoZ':
      bottom_list = recipe.recipe_set.all().order_by('name')
    else:
      bottom_list = recipe.recipe_set.all().order_by('averageRating').reverse()
      sortby = 'HighestRated'

    bottom = "ReciCopies"

  instructions = recipe.instruction_set.order_by('id')

  
  itemsPerPage = 5

  ret = getItemListAndPageList(bottom_list, itemsPerPage, request)
  bottom_list = ret[0]
  pages = ret[1]

  context = { 'bottom_list': bottom_list,
              'pages':pages,
              'sortby':sortby,
              'recipe':recipe,
              'review':review, 
              'bottom':bottom,
              'instructions':instructions }
  return render(request, 'recipe/recipeDetail.html', context)
  
'''def recipeReviews(request, recipe_id):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  return render(request, 'recipe/recipeReviews.html', {'recipe':recipe})'''

def chefIndex(request, sortby = 'Newest'):
  if sortby == 'AtoZ':
    chef_list = Chef.objects.all().order_by('username')
  else: # sortby == 'Newest'
    chef_list = Chef.objects.all().order_by('id').reverse()
    sortby = 'Newest'

  chefsPerPage = 10

  ret = getItemListAndPageList(chef_list, chefsPerPage, request)
  chefs = ret[0]
  pages = ret[1]

  context = { 'chef_list' : chefs,
              'pages' : pages,
              'sortby': sortby , }
  return render(request, 'recipe/chefIndex.html', context)

def chefDetail(request, chef_id, showrecipes = 'Originals'):
  chef = get_object_or_404(Chef, pk=chef_id)
  if showrecipes == 'Favorites':
    recipe_list = []
    fav_list = Chef_favoriteRecipes.objects.filter(chef_id=chef_id).order_by('id').reverse()
    for fav in fav_list:
      recipe_list.append(fav.recipe)
  elif showrecipes == 'ReciCopies':
    recipe_list = chef.recipe_set.all().exclude(previousVersion__exact=None)
  else: # Originals
    recipe_list = chef.recipe_set.all().filter(previousVersion__exact=None)
    showrecipes = 'Originals'

  recipesPerPage = 5

  ret = getItemListAndPageList(recipe_list, recipesPerPage, request)
  recipes = ret[0]
  pages = ret[1]

  context = { 'chef':chef,
              'recipe_list': recipes,
              'pages':pages,
              'showrecipes':showrecipes,}

  return render(request, 'recipe/chefDetail.html', context)

''' links used now
def getPic(request, pic_name):
  api = BasicClient('VATx6OASrU4KYLaWshrxIvyyYUIl8x','xkpKJ3Wti1cXilKJYnMSqaOLvmNnwe')
  pic = api.get('/path/data/images/',pic_name)
  #img = zlib.decompress(pic.data, 16+zlib.MAX_WBITS)
  img = pic.data
  response = HttpResponse(img, content_type='image')
  return response'''

def addChef(request):
  if request.method == 'POST':
    print request.FILES
    form = forms.AddChef(request.POST, request.FILES)
    if form.is_valid():
      username = form.cleaned_data['username']
      password = form.cleaned_data['password1']
      email = form.cleaned_data['email']
      newChef = Chef.objects.create_user(username,email,password)
      newChef.first_name = form.cleaned_data['first_name']
      newChef.last_name = form.cleaned_data['last_name']
      newChef.save()
      user = authenticate(username=username,password=password)


      t = Thread(target=addChefAPICalls, args=(newChef,request,username))
      t.start()


      # assuming authenticate works
      login(request, user)
      return HttpResponseRedirect('/chefs/'+str(newChef.id))
  else:
    form = forms.AddChef()
  return render(request, 'recipe/addChef.html', {'form':form})

def addChefAPICalls(newChef,request,username):
  api = BasicClient('VATx6OASrU4KYLaWshrxIvyyYUIl8x','xkpKJ3Wti1cXilKJYnMSqaOLvmNnwe')

  #make folder for pictures
  pictureFolder = '/ChefPicture/'+str(newChef.id)+'/'
  api.post('/path/oper/mkdir',path=pictureFolder)

  p = request.FILES['chef_picture']
  picName = p.name.split(".")
  tempPictureName = "tmp."+picName[-1]
  with open(tempPictureName, 'wb+') as destination:
    for chunk in p.chunks():
      destination.write(chunk)

  destination.close()
  #im = Image.open(StringIO(file(tempPictureName,"rb").read())) 
  im = Image.open(tempPictureName)
  size = 64, 64
  im.save(picName[0]+"."+picName[-1], "JPEG", quality=30)
  im.thumbnail(size, Image.ANTIALIAS)
  im.save("thumb.jpg", "JPEG")

  #upload picture
  fileName = username+'_'+picName[0]+'.'+picName[-1]
  api.post('/path/data'+pictureFolder, file=(fileName, open(picName[0]+"."+picName[-1], 'r').read()))
  api.post('/path/data'+pictureFolder, file=(picName[0]+'_thumb.jpg', open('thumb.jpg', 'r').read()))

  rpic = ChefPicture.objects.create(chef=newChef)
  rpic.setPath(fileName, pictureFolder)
  rpic.setSmallPath(picName[0]+'_thumb.jpg', pictureFolder)

  os.system("rm "+tempPictureName)

@login_required(login_url='/login/')
def addToFavorites(request, recipe_id):
  #does this check in case they tried to add to favorites when logged out
  if Recipe.objects.get(id=recipe_id) not in Chef.objects.get(id=request.user.id).recipe_set.all():
    Chef_favoriteRecipes.objects.create(chef_id=request.user.id,recipe_id=recipe_id)
  return HttpResponseRedirect('/recipes/'+str(recipe_id))

@login_required(login_url='/login/')
def removeFromFavorites(request, recipe_id):
  fav = Chef_favoriteRecipes.objects.get(chef_id=request.user.id,recipe_id=recipe_id)
  fav.delete()
  nextPage = request.GET.get('next')
  return HttpResponseRedirect(nextPage)

''' need to change this to a simpler form
def editChef(request):
  if request.method == 'POST':
    form = UserChangeForm(request.POST)
    if form.is_valid():
      print form.cleaned_data
      return HttpResponseRedirect('/chefs/')#+str(newChef.id))
  else:
    form = UserChangeForm()
  return render(request, 'recipe/editChef.html', {'form':form})'''

@login_required(login_url='/login/')
def addReview(request,recipe_id):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  if request.method == 'POST':
    comment = request.POST.get('Comment')
    rating = request.POST.get('staraddStars')
    revList = recipe.review_set.filter(chef_id=request.user.id)
    if revList.count() > 0:
      review = revList[0]
      review.comment = comment
      review.rating = rating
      review.save()
    else:
      recipe.review_set.create(comment=comment,rating=rating,chef_id=request.user.id)
    return HttpResponseRedirect('/recipes/'+str(recipe_id))

''' unused because using django's login function in urls
def login(request):
  if request.method == 'POST':
    form = forms.Login(request.POST, request.FILES)
    if form.is_valid():
      username = form.cleaned_data['username']
      pw = form.cleaned_data['password']

      try:
        chef = Chef.objects.get(name=username)
      except ObjectDoesNotExist:
        return HttpResponseRedirect('/login')

      if chef.password == pw:
        request.session['username'] = username
      else:
        return HttpResponseRedirect('/login')

appRecipe/templates/recipe/addChef.html
{% extends "recipe/base.html" %}

{% block title %}Add New Chef{% endblock title %}

{% block content %}

<form action="/chefs/add/" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock content %}

appRecipe/templates/recipe/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet/less" type="text/css" href="{% static 'bootstrap/less/bootstrap.less' %}" /><script src="{% static 'less/less-1.3.3.min.js' %}" ></script>
  <link rel="stylesheet" type="text/css" href="{% static 'starRating/jquery.rating.css' %}" />
  <!-- put body padding here if we have a fixed bar on top/bottom -->
  <!-- put responsive bootstrap css link here if needed -->
  {% block extrahead %}
  
  {% endblock extrahead %}
</head>

<body>
  
    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
        <a class="brand" href="{% url 'home' %}">ReciCopy</a>
        <ul class="nav">
          <li class="{% block RecipeIndexActive %}{% endblock %}"><a href="{% url 'recipeIndex' %}">Recipes</a></li>
          <li class="{% block ChefIndexActive %}{% endblock %}"><a href="{% url 'chefIndex' %}">Chefs</a></li>
        </ul>
        <form class="navbar-search pull-right" action="/search/" method="get">
          <input name="q" id="id_q" type="text" class="search-query" placeholder="Search" value="{% if query %}{{query}}{% endif %}"/>
        </form>
        <ul class="nav pull-right">
          {% if user.is_authenticated %}
          <li class="dropdown">
            <a id="userDropDown" class="dropdown-toggle" href="#" data-toggle="dropdown" role="button">{{ user.username }}<b class="caret" ></b>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="userDropDown">
              <li><a href="{% url 'addRecipe' %}">New Recipe</a></li>
              <li><a href="{% url 'chefDetail' user.id %}">Profile</a></li>
              <li class="divider" />
              <li><a href="/logout/">Logout</a></li>
            </ul>
          </li>            
          {% else %}
          <li><a href='/login/'>Login</a></li>
          <li><a href='/chefs/add/'>Register</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
<div class="container redwell">
    <div id="content">
      {% block content %}<p>Default content, replace in page.</p>{% endblock content %}
    </div>
  </div>

  <!-- JS at end, so pages load faster -->
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'recipe/form.js' %}"></script>
  <script type="text/javascript" src="{% static 'starRating/jquery.rating.pack.js' %}" ></script>
  <script type="text/javascript" src="{% static 'starRating/jquery.MetaData.js' %}" ></script>
</body></html>

appRecipe/templates/recipe/editChef.html
{% extends "recipe/base.html" %}

{% block title %}Edit Information{% endblock title %}

{% block content %}

<form action="/chefs/edit/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock content %}

appRecipe/templates/recipe/editRecipe.html
{% extends "recipe/base.html" %}
{% load dajaxice_templatetags %}
{% load appRecipe_extras %}
{% load set_var %}


{% block title %}Edit {{name}}{% endblock title %}
{% block extrahead %}
  {% dajaxice_js_import %}
  {% endblock extrahead %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
	{{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.recipe_Name.errors }}
        <label for="id_recipe_Name">Recipe Name:</label>
        {{ form.recipe_Name }}
    </div>
    <div class="fieldWrapper">
        {{ form.prep_Time.errors }}
        <label for="id_prep_Time">Prep Time:</label>
        {{ form.prep_Time }}
    </div>
    <div class="fieldWrapper">
        {{ form.cook_Time.errors }}
        <label for="id_cook_Time">Cook Time:</label>
        {{ form.cook_Time }}
    </div>
    <div class="fieldWrapper">
        {{ form.comments.errors }}
        <label for="id_comments">Chef Comments:</label>
        {{ form.comments }}
    </div>
    

    <div id="pics">
        {% for p in initialPics %}
       <div> <img style="width:64px;height:64px;" picid={{p.id}} src={{p.path}} class="img-polaroid">

        <a class='btn' onclick='Dajaxice.appRecipe.deletePic(null, {"id":{{p.id}}});'><i class="icon-trash"></i></a></div>
        {% endfor %}
    </div>

    <button id="add-pic" type="button">Add Another Picture</button>
   
    <div id="ingredients">


		<label for="id_extra_ings_0">Ingredients:</label>

        {% for i in initialIngredients %}
    	<div class="fieldWrapper">
	        <input placeholder="Ingredient Name" value="{{i.name}}" id="extra_ings_{{forloop.counter0}}" name="extra_ings_{{forloop.counter0}}" type="text" data-provide="typeahead" data-source="{{ ingredients }}" autocomplete="off"> <input type="text" placeholder="Amount" value="{{i.amount}}" id="amount_extra_ings_{{forloop.counter0}}" name="amount_extra_ings_{{forloop.counter0}}"> <select id="unit_extra_ings_{{forloop.counter0}}" name="unit_extra_ings_{{forloop.counter0}}">
  					{% for u in units %}

  					<option {%if u.name in i.unit.name %}selected{%endif%} value="{{ u.name }}">{{ u.name }}</option>
  					{% endfor %}
					</select>
	        
	    </div>

        {% endfor %}


    </div>
    <div id="unitss" style="display:none;">
    	{% for u in units %}
  					<option value="{{ u.name }}">{{ u.name }}</option>
  					{% endfor %}
    </div>
	<button id="add-ing" type="button">Add Ingredient</button>

    <div id="steps">
    <div class="fieldWrapper">
        {{ form.instructions.errors }}
        <label for="id_instructions">Step 1:</label>
        {{ form.instructions }}
    </div>
    {{steps|init}}
    {% for field in form %}
    {% if 'field' in field.html_name %}
    <div class="fieldWrapper">
        <label>Step {{ steps|next }}:</label> {{ field }}
    </div>
    {% endif %}
{% endfor %}

    <input id="ingre" type="hidden" value="{{ingredients}}">
</div>
<button id="add-another" type="button">Add Step</button>

<div class="fieldWrapper">
        {{ form.inst.errors }}
        <label for="id_inst"></label>
        {{ form.inst }}
    </div>
    <div class="fieldWrapper">
        {{ form.ings.errors }}
        <label for="id_ings"></label>
        {{ form.ings }}
    </div>
    <input id="id_pic" name="pic" value="0" type="hidden">
<input type="submit" value="Submit" />
</form>



{% endblock content %}

appRecipe/templates/recipe/recipePDF.html
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>

<img src="{{ recipe.mainPicture.smallpath }}" alt="Main Recipe Picture" class="img-polaroid">

<h1>{{ recipe.name }}</h1>

<p>"{{ recipe.chefComment }}" - <a href="{% url 'chefDetail' recipe.chef.id %}">{{ recipe.chef.username }}</a></p>

<h4>Prep Time</h4>
<p>{{ recipe.prepTimeString }}</p>
<h4>Cook Time</h4>
<p>{{ recipe.cookTimeString }}</p>
<h4>Total Time</h4>
<p>{{ recipe.totalTimeString }}</p>

<h2>Ingredients</h2>
{% if recipe.recipeingredient_set.all %}
<ul>
{% for ri in recipe.recipeingredient_set.all %}
<li>{{ ri.amount }} {{ ri.unit.name }}{{ ri.amount|pluralize }} of {{ ri.ingredient.name }}</li>
{% endfor %}
</ul>
{% else %}
<p>No ingredients</p>
{% endif %}

<h2>Instructions</h2>
{% if recipe.instruction_set.all %}
{% for ri in recipe.instruction_set.all %}
{{forloop.counter}}. {{ ri.text }}
{% endfor %}
{% else %}
<p>No instructions.</p>
{% endif %}

</body></html>